### ISSUE TITLE
Complete rebirth to support cloud integration

### ISSUE THREAD

**Issue by cyberbit** [cyberbit/modation#134]
Modation SAM (super secret serverless scraper-as-a-service for Soundation) will allow the extension to completely let go of scraping, polling, and notification responsibilities, as the watchlist will now be operated in the cloud. Because these were the main draw of Modation, the extension's features as they stand will be nuked from orbit. This issue will track Phase 1 of the below roadmap:

### Phase 1
- [x] modern Vue and webpack tooling
- [x] navigation detection and ID (track, group, etc.)
- [x] passive sync with [modation.app](https://modation.app) (ping when navigating to supported URLs)
- [x] fix CORS issues with above
- [x] disable options page
- [ ] basic stats for active tab in popup
- [ ] show basic login information in popup
- [x] add support for CollabGroupView
- [ ] new about page on update, explaining the above plan

### Phase 2
- discord login via popup
- active sync with modation.app (when authenticated, POST page source to API)
- add/remove watchlist items on track and group pages
- manage watchlist in options, persist to modation.app
- Modation SAM: link discord profile to soundation profile
- Modation SAM: detect updates on watched track, group, etc. and deliver notifications
